# Sample Docker Compose for 
version: '3.0'

services:
  db:
    image: postgres
    restart: always
    volumes:
        - pg_data:/some/location
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "sample"
      POSTGRES_DB: "mydb"
      PGPORT: "5431"
      PGHOST: "localhost"
      DB_DATABASE: "database"
      DB_USERNAME: "username"
      DB_PASSWORD: "password"
    ports:
        - 5434:5431
  pgadmin4:
    volumes:
      - pgadmin_data:/some/location
    image: dpage/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
        - 81:80
  adminer:
    image: adminer
    environment:
      DB_CONNECTION: "pgsql"
      DB_HOST: "db"
      DB_PORT: "543q"
      DB_DATABASE: "postgres"
      DB_USERNAME: "user"
      DB_PASSWORD: "secret"
    ports:
      - 8081:8080
volumes:
    pg_data:
    pgadmin_data:
